# Form implementation generated from reading ui file 'C:\Users\LENOVO\PycharmProjects\pythonProject2\tttt\tttt\frame4_fixed.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Frame.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 776)
        MainWindow.setStyleSheet("margin: 0px")
        self.centralwidget_4 = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget_4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"magin: 0px\n"
"\n"
"#image_label_4 {\n"
"background-image: url(:/imgs/Assets/image/Group 46.png)\n"
"}")
        self.centralwidget_4.setObjectName("centralwidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.image_frame_4 = QtWidgets.QFrame(parent=self.centralwidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_frame_4.sizePolicy().hasHeightForWidth())
        self.image_frame_4.setSizePolicy(sizePolicy)
        self.image_frame_4.setMinimumSize(QtCore.QSize(662, 725))
        self.image_frame_4.setStyleSheet("QFrame {\n"
"    padding: 0px; /* Xóa khoảng cách bên trong */\n"
"}\n"
"")
        self.image_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.image_frame_4.setObjectName("image_frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.image_frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label_4 = QtWidgets.QLabel(parent=self.image_frame_4)
        self.image_label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.image_label_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.image_label_4.setStyleSheet("\n"
"border-image: url(:/imgs/Assets/image/Group 50.png);\n"
"width: 100%;\n"
"height: 100%;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"background-position: center;")
        self.image_label_4.setText("")
        self.image_label_4.setScaledContents(False)
        self.image_label_4.setObjectName("image_label_4")
        self.horizontalLayout.addWidget(self.image_label_4)
        self.horizontalLayout_3.addWidget(self.image_frame_4)
        self.right_frame_4 = QtWidgets.QFrame(parent=self.centralwidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_frame_4.sizePolicy().hasHeightForWidth())
        self.right_frame_4.setSizePolicy(sizePolicy)
        self.right_frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.right_frame_4.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"sizePolicy: 50%;\n"
"")
        self.right_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.right_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.right_frame_4.setObjectName("right_frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.login_frame_5 = QtWidgets.QFrame(parent=self.right_frame_4)
        self.login_frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_frame_5.setObjectName("login_frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.login_label_4 = QtWidgets.QLabel(parent=self.login_frame_5)
        self.login_label_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.login_label_4.setFont(font)
        self.login_label_4.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"margin-bottom: 30px\n"
"")
        self.login_label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_label_4.setObjectName("login_label_4")
        self.verticalLayout_3.addWidget(self.login_label_4)
        self.account_frame_4 = QtWidgets.QFrame(parent=self.login_frame_5)
        self.account_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.account_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.account_frame_4.setObjectName("account_frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.account_frame_4)
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.username_lineEdit_4 = QtWidgets.QLineEdit(parent=self.account_frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStrikeOut(False)
        self.username_lineEdit_4.setFont(font)
        self.username_lineEdit_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom:1px;\n"
"border: 2px solid rgba(46,82,101,200);\n"
"border-radius: 15px;\n"
"margin: 0;\n"
"padding-left: 4px")
        self.username_lineEdit_4.setText("")
        self.username_lineEdit_4.setFrame(True)
        self.username_lineEdit_4.setClearButtonEnabled(False)
        self.username_lineEdit_4.setObjectName("username_lineEdit_4")
        self.verticalLayout_2.addWidget(self.username_lineEdit_4)
        self.asswordlineEdit_4 = QtWidgets.QLineEdit(parent=self.account_frame_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStrikeOut(False)
        self.asswordlineEdit_4.setFont(font)
        self.asswordlineEdit_4.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: rgba(0,0,0,240);\n"
"padding-bottom:1px;\n"
"border: 2px solid rgba(46,82,101,200);\n"
"border-radius: 15px;\n"
"padding-left: 4px")
        self.asswordlineEdit_4.setText("")
        self.asswordlineEdit_4.setFrame(True)
        self.asswordlineEdit_4.setClearButtonEnabled(False)
        self.asswordlineEdit_4.setObjectName("asswordlineEdit_4")
        self.verticalLayout_2.addWidget(self.asswordlineEdit_4)
        self.verticalLayout_3.addWidget(self.account_frame_4)
        self.verticalLayout.addWidget(self.login_frame_5)
        self.role_frame_4 = QtWidgets.QFrame(parent=self.right_frame_4)
        self.role_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.role_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.role_frame_4.setObjectName("role_frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.role_frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 23, 14)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox = QtWidgets.QComboBox(parent=self.role_frame_4)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(2, 60, 3);  /* Màu nền xanh lá */\n"
"    color: white;  /* Màu chữ trắng */\n"
"    border-radius: 5px; \n"
"    padding: 0px 10px;\n"
"    font-size: 16px;\n"
"    min-width: 20px; \n"
"    min-height: 35px; \n"
"    border: 2px solid #2E7D32;\n"
"border: none;\n"
"}\n"
" QComboBox::drop-down {\n"
"border: none;\n"
"background: transparent;\n"
"margin-left: -15px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: url(:/white_icons/Assets/feather(1)/chevron-down.svg)\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.role_frame_4, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.login_frame_4 = QtWidgets.QFrame(parent=self.right_frame_4)
        self.login_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_frame_4.setObjectName("login_frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.login_frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_pushButton_4 = QtWidgets.QPushButton(parent=self.login_frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pushButton_4.sizePolicy().hasHeightForWidth())
        self.login_pushButton_4.setSizePolicy(sizePolicy)
        self.login_pushButton_4.setMaximumSize(QtCore.QSize(547, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.login_pushButton_4.setFont(font)
        self.login_pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #0D470D;\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;   \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1B5E20; \n"
"}")
        self.login_pushButton_4.setObjectName("login_pushButton_4")
        self.horizontalLayout_2.addWidget(self.login_pushButton_4)
        self.verticalLayout.addWidget(self.login_frame_4, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.right_frame_4)
        MainWindow.setCentralWidget(self.centralwidget_4)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label_4.setText(_translate("MainWindow", "LOGIN"))
        self.username_lineEdit_4.setPlaceholderText(_translate("MainWindow", "Username"))
        self.asswordlineEdit_4.setPlaceholderText(_translate("MainWindow", "Password"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Role"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Staff"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Manager"))
        self.login_pushButton_4.setText(_translate("MainWindow", "Login"))
