# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame7.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 691)
        MainWindow.setStyleSheet("* {\n"
"color: #fff}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color: rgb(2, 50, 21);\n"
"}\n"
"#frame_17 {\n"
"background-color: rgb(40, 207, 107);\n"
"padding: 0 0px;\n"
"}\n"
"#Menu_btn {\n"
"background-color: rgb(40, 207, 107);\n"
"border-radius: 4px;\n"
"margin: 10px 0;\n"
"}\n"
"#customer_id_input_7, #product_id_input_7,#quantity_input_7, #price_input_7, #payment_method_select_7, #product_category_select_7, #discount_applied_input_7, #total_amount_input_7 {\n"
"border-radius: 6px;\n"
"background-color: rgb(225, 253, 234);\n"
"height: 46px;\n"
"width: 200px;\n"
"color: #000;\n"
"font-size: 25px;\n"
"font-family: Segoe UI Semibold;\n"
"padding-right: 5px;\n"
"cursor: IBeam;\n"
"}\n"
" QComboBox::drop-down {\n"
"border: none;\n"
"background: transparent;\n"
"margin-left: -15px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: url(:/icons/Assets/feather/chevron-down.svg)\n"
"}\n"
"\n"
"#real_date_label_7, #real_time_label_7 {\n"
"background-color: rgb(243, 221, 214);\n"
"color: #000;\n"
"border-radius: 6px;\n"
"}\n"
"#real_date_label_7 {\n"
"    margin-right: 16px;\n"
"}\n"
"#real_time_label_7 {\n"
"    margin-left: 16px;\n"
"}\n"
"#add_data_button_7, #delete_data_button_7, #table_view_button_7 {\n"
"    background-color: rgb(40, 207, 107);\n"
"    border-radius: 6px;\n"
"    color: #000;\n"
"    padding:16px 0;\n"
"}\n"
"\n"
"#add_data_button_7:hover, #delete_data_button_7:hover, #table_view_button_7:hover {\n"
"background-color: rgb(225, 253, 234);\n"
"}\n"
"\n"
"#add_data_button_7:pressed, #delete_data_button_7:pressed, #table_view_button_7:pressed {\n"
"background-color: rgb(185, 240, 214);\n"
"}\n"
"\n"
"\n"
"#add_data_button_7, #delete_data_button_7 {\n"
"    margin-right: 8px;\n"
"}\n"
"#label_12 {\n"
"    width: 120px;\n"
"    height: 120px;\n"
"}\n"
"#transaction_button_7, #member_button_7, #analyze_button_7, #log_out_button_7{\n"
"background-color: rgb(40, 207, 107);\n"
"border-radius: 0px;\n"
"color: #000;\n"
"padding: 0 15px;\n"
"text-align: left;\n"
"font-family: Segoe UI Semibold;\n"
"font-size: 20px;\n"
"}\n"
"#transaction_button_7 {\n"
" background-color: rgb(227, 255, 236);\n"
"margin: 0px;\n"
"padding: 8px 3px;\n"
"\n"
"}\n"
"#frame_16 {\n"
"margin:0\n"
"}\n"
"\n"
"#transaction_button_7, #member_button_7, #analyze_button_7 {\n"
"\n"
"margin-left: 0px;\n"
"padding: 8px 3px;\n"
"}\n"
"#log_out_button_7 {\n"
"text-align: center8px;\n"
"padding: 8px 15px }\n"
"#transaction_button_7:hover,#member_button_7:hover,#analyze_button_7:hover,#log_out_button_7:hover {\n"
"background-color: white}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left_Menu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_Menu.sizePolicy().hasHeightForWidth())
        self.Left_Menu.setSizePolicy(sizePolicy)
        self.Left_Menu.setMinimumSize(QtCore.QSize(165, 0))
        self.Left_Menu.setMaximumSize(QtCore.QSize(165, 16777215))
        self.Left_Menu.setObjectName("Left_Menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Left_Menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_17 = QtWidgets.QFrame(self.Left_Menu)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_17)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_14.setSpacing(13)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        self.label_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/imgs/Assets/image/Group 73.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.frame_14.setFont(font)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(35)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.transaction_button_7 = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.transaction_button_7.setFont(font)
        self.transaction_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transaction_button_7.setStyleSheet("background-color: white\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/airplay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transaction_button_7.setIcon(icon)
        self.transaction_button_7.setIconSize(QtCore.QSize(25, 25))
        self.transaction_button_7.setObjectName("transaction_button_7")
        self.verticalLayout_5.addWidget(self.transaction_button_7)
        self.member_button_7 = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.member_button_7.setFont(font)
        self.member_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.member_button_7.setIcon(icon1)
        self.member_button_7.setIconSize(QtCore.QSize(25, 25))
        self.member_button_7.setObjectName("member_button_7")
        self.verticalLayout_5.addWidget(self.member_button_7)
        self.analyze_button_7 = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.analyze_button_7.setFont(font)
        self.analyze_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/activity.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analyze_button_7.setIcon(icon2)
        self.analyze_button_7.setIconSize(QtCore.QSize(25, 25))
        self.analyze_button_7.setObjectName("analyze_button_7")
        self.verticalLayout_5.addWidget(self.analyze_button_7)
        self.verticalLayout_6.addWidget(self.frame_16, 0, QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.log_out_button_7 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.log_out_button_7.setFont(font)
        self.log_out_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_out_button_7.setIcon(icon3)
        self.log_out_button_7.setObjectName("log_out_button_7")
        self.horizontalLayout_15.addWidget(self.log_out_button_7)
        self.verticalLayout_6.addWidget(self.frame_18)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.verticalLayout_4.addWidget(self.frame_17)
        self.horizontalLayout.addWidget(self.Left_Menu)
        self.Main_Body = QtWidgets.QWidget(self.centralwidget)
        self.Main_Body.setObjectName("Main_Body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main_Body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_frame = QtWidgets.QWidget(self.Main_Body)
        self.btn_frame.setObjectName("btn_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.btn_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.btn_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.frame_10.setFont(font)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.btn_frame, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.time_frame = QtWidgets.QWidget(self.Main_Body)
        self.time_frame.setObjectName("time_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.time_frame)
        self.gridLayout.setContentsMargins(0, 0, 90, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.time_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(64, 0, 11, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.customer_id_input_7 = QtWidgets.QLineEdit(self.frame_2)
        self.customer_id_input_7.setMaximumSize(QtCore.QSize(194, 46))
        self.customer_id_input_7.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.customer_id_input_7.setObjectName("customer_id_input_7")
        self.horizontalLayout_4.addWidget(self.customer_id_input_7)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.time_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777213, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.product_id_input_7 = QtWidgets.QComboBox(self.frame_4)
        self.product_id_input_7.setMaximumSize(QtCore.QSize(194, 16777215))
        self.product_id_input_7.setStyleSheet("color: black;\n"
"padding-left: 5px")
        self.product_id_input_7.setObjectName("product_id_input_7")
        self.product_id_input_7.addItem("")
        self.product_id_input_7.addItem("")
        self.product_id_input_7.addItem("")
        self.product_id_input_7.addItem("")
        self.product_id_input_7.addItem("")
        self.horizontalLayout_5.addWidget(self.product_id_input_7)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.time_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.total_amount_input_7 = QtWidgets.QLineEdit(self.frame_9)
        self.total_amount_input_7.setMaximumSize(QtCore.QSize(194, 46))
        self.total_amount_input_7.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.total_amount_input_7.setObjectName("total_amount_input_7")
        self.horizontalLayout_10.addWidget(self.total_amount_input_7)
        self.gridLayout.addWidget(self.frame_9, 3, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.time_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.quantity_input_7 = QtWidgets.QLineEdit(self.frame_6)
        self.quantity_input_7.setMaximumSize(QtCore.QSize(194, 46))
        self.quantity_input_7.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.quantity_input_7.setObjectName("quantity_input_7")
        self.horizontalLayout_7.addWidget(self.quantity_input_7)
        self.gridLayout.addWidget(self.frame_6, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.time_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.product_category_select_7 = QtWidgets.QComboBox(self.frame_5)
        self.product_category_select_7.setMaximumSize(QtCore.QSize(194, 16777215))
        self.product_category_select_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.product_category_select_7.setStyleSheet("color: black;\n"
"padding-left: 5px")
        self.product_category_select_7.setObjectName("product_category_select_7")
        self.product_category_select_7.addItem("")
        self.product_category_select_7.addItem("")
        self.product_category_select_7.addItem("")
        self.product_category_select_7.addItem("")
        self.product_category_select_7.addItem("")
        self.horizontalLayout_6.addWidget(self.product_category_select_7)
        self.gridLayout.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.time_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.discount_applied_input_7 = QtWidgets.QLineEdit(self.frame_7)
        self.discount_applied_input_7.setMaximumSize(QtCore.QSize(194, 46))
        self.discount_applied_input_7.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.discount_applied_input_7.setObjectName("discount_applied_input_7")
        self.horizontalLayout_8.addWidget(self.discount_applied_input_7)
        self.gridLayout.addWidget(self.frame_7, 2, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.time_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.payment_method_select_7 = QtWidgets.QComboBox(self.frame_3)
        self.payment_method_select_7.setMaximumSize(QtCore.QSize(194, 16777215))
        self.payment_method_select_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.payment_method_select_7.setStyleSheet("color: black;\n"
"padding-left: 5px")
        self.payment_method_select_7.setObjectName("payment_method_select_7")
        self.payment_method_select_7.addItem("")
        self.payment_method_select_7.addItem("")
        self.payment_method_select_7.addItem("")
        self.payment_method_select_7.addItem("")
        self.payment_method_select_7.addItem("")
        self.horizontalLayout_3.addWidget(self.payment_method_select_7)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.time_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setContentsMargins(64, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.price_input_7 = QtWidgets.QLineEdit(self.frame_8)
        self.price_input_7.setMaximumSize(QtCore.QSize(194, 46))
        self.price_input_7.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.price_input_7.setObjectName("price_input_7")
        self.horizontalLayout_9.addWidget(self.price_input_7)
        self.gridLayout.addWidget(self.frame_8, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.time_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.Main_Body)
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_11 = QtWidgets.QFrame(self.widget)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.real_date_label_7 = QtWidgets.QLabel(self.frame_11)
        self.real_date_label_7.setMaximumSize(QtCore.QSize(194, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.real_date_label_7.setFont(font)
        self.real_date_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.real_date_label_7.setObjectName("real_date_label_7")
        self.horizontalLayout_12.addWidget(self.real_date_label_7)
        self.real_time_label_7 = QtWidgets.QLabel(self.frame_11)
        self.real_time_label_7.setMaximumSize(QtCore.QSize(97, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.real_time_label_7.setFont(font)
        self.real_time_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.real_time_label_7.setObjectName("real_time_label_7")
        self.horizontalLayout_12.addWidget(self.real_time_label_7)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_12.addWidget(self.frame_13)
        self.horizontalLayout_11.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.widget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.add_data_button_7 = QtWidgets.QPushButton(self.frame_12)
        self.add_data_button_7.setMaximumSize(QtCore.QSize(155, 64))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.add_data_button_7.setFont(font)
        self.add_data_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_data_button_7.setObjectName("add_data_button_7")
        self.horizontalLayout_13.addWidget(self.add_data_button_7)
        self.delete_data_button_7 = QtWidgets.QPushButton(self.frame_12)
        self.delete_data_button_7.setMaximumSize(QtCore.QSize(212, 64))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.delete_data_button_7.setFont(font)
        self.delete_data_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_data_button_7.setObjectName("delete_data_button_7")
        self.horizontalLayout_13.addWidget(self.delete_data_button_7)
        self.table_view_button_7 = QtWidgets.QPushButton(self.frame_12)
        self.table_view_button_7.setMaximumSize(QtCore.QSize(212, 64))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.table_view_button_7.setFont(font)
        self.table_view_button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_view_button_7.setObjectName("table_view_button_7")
        self.horizontalLayout_13.addWidget(self.table_view_button_7)
        self.horizontalLayout_11.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.Main_Body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.transaction_button_7.setText(_translate("MainWindow", "Transaction"))
        self.member_button_7.setText(_translate("MainWindow", "Member"))
        self.analyze_button_7.setText(_translate("MainWindow", "Analyze"))
        self.log_out_button_7.setText(_translate("MainWindow", "LOG OUT"))
        self.label_11.setText(_translate("MainWindow", "TRANSACTION DATA"))
        self.label.setText(_translate("MainWindow", "Customer ID:  "))
        self.label_2.setText(_translate("MainWindow", "Product ID: "))
        self.product_id_input_7.setItemText(0, _translate("MainWindow", "Select"))
        self.product_id_input_7.setItemText(1, _translate("MainWindow", "A"))
        self.product_id_input_7.setItemText(2, _translate("MainWindow", "B"))
        self.product_id_input_7.setItemText(3, _translate("MainWindow", "C"))
        self.product_id_input_7.setItemText(4, _translate("MainWindow", "D"))
        self.label_8.setText(_translate("MainWindow", "Total Amount:"))
        self.label_3.setText(_translate("MainWindow", "Quantity: "))
        self.label_7.setText(_translate("MainWindow", "Product Category:"))
        self.product_category_select_7.setItemText(0, _translate("MainWindow", "Select"))
        self.product_category_select_7.setItemText(1, _translate("MainWindow", "Clothing"))
        self.product_category_select_7.setItemText(2, _translate("MainWindow", "Books"))
        self.product_category_select_7.setItemText(3, _translate("MainWindow", "Electronics"))
        self.product_category_select_7.setItemText(4, _translate("MainWindow", "Home Decor"))
        self.label_5.setText(_translate("MainWindow", "Discount Applied:"))
        self.label_6.setText(_translate("MainWindow", "Payment Method:"))
        self.payment_method_select_7.setItemText(0, _translate("MainWindow", "Select"))
        self.payment_method_select_7.setItemText(1, _translate("MainWindow", "cash"))
        self.payment_method_select_7.setItemText(2, _translate("MainWindow", "PayPal"))
        self.payment_method_select_7.setItemText(3, _translate("MainWindow", "Credit Card"))
        self.payment_method_select_7.setItemText(4, _translate("MainWindow", "Debit Card"))
        self.label_4.setText(_translate("MainWindow", "Price: "))
        self.real_date_label_7.setText(_translate("MainWindow", "Date"))
        self.real_time_label_7.setText(_translate("MainWindow", "Time"))
        self.add_data_button_7.setText(_translate("MainWindow", "Add data"))
        self.delete_data_button_7.setText(_translate("MainWindow", "Delete data"))
        self.table_view_button_7.setText(_translate("MainWindow", "Table View"))
import Frame.resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
