# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_PyQt/frame1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 810)
        MainWindow.setStyleSheet("* {\n"
"color: #fff}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color: rgb(2, 50, 21);\n"
"}\n"
"#frame_17 {\n"
"background-color: rgb(40, 207, 107);\n"
"padding: 0 0px;\n"
"}\n"
"#Menu_btn {\n"
"background-color: rgb(40, 207, 107);\n"
"border-radius: 4px;\n"
"margin: 10px 0;\n"
"}\n"
"#lineEdit,#lineEdit_2,#lineEdit_3,#lineEdit_4,#comboBox,#comboBox_2,#lineEdit_7,#lineEdit_8 {\n"
"border-radius: 6px;\n"
"background-color: rgb(225, 253, 234);\n"
"height: 46px;\n"
"width: 200px;\n"
"color: #000;\n"
"font-size: 25px;\n"
"font-family: Segoe UI Semibold;\n"
"padding-right: 5px;\n"
"cursor: IBeam;\n"
"}\n"
" QComboBox::drop-down {\n"
"border: none;\n"
"background: transparent;\n"
"margin-left: -15px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: url(:/icons/Assets/feather/chevron-down.svg)\n"
"}\n"
"\n"
"#label_9,#label_10 {\n"
"background-color: rgb(243, 221, 214);\n"
"color: #000;\n"
"border-radius: 6px;\n"
"}\n"
"#label_9 {\n"
"    margin-right: 16px;\n"
"}\n"
"#label_10 {\n"
"    margin-left: 16px;\n"
"}\n"
"#refresh_btn_1, #pushButton_2, #pushButton_3 {\n"
"    background-color: rgb(40, 207, 107);\n"
"    border-radius: 6px;\n"
"    color: #000;\n"
"    padding:16px 0;\n"
"}\n"
"\n"
"#refresh_btn_1:hover, #pushButton_2:hover, #pushButton_3:hover {\n"
"background-color: rgb(225, 253, 234);\n"
"}\n"
"\n"
"#refresh_btn_1, #pushButton_2 {\n"
"    margin-right: 8px;\n"
"}\n"
"#label_12 {\n"
"    width: 120px;\n"
"    height: 120px;\n"
"}\n"
"#analyze_pushButton_1,#member_pushButton_1,#transaction_pushButton_1,#logout_button_1 {\n"
"background-color: rgb(40, 207, 107);\n"
"border-radius: 0px;\n"
"color: #000;\n"
"padding: 0 15px;\n"
"text-align: left;\n"
"font-family: Segoe UI Semibold;\n"
"font-size: 20px;\n"
"}\n"
"#transaction_pushButton_1 {\n"
" background-color: white;\n"
"margin: 0px;\n"
"padding: 8px 3px;\n"
"\n"
"}\n"
"#frame_16 {\n"
"margin:0\n"
"}\n"
"\n"
"#analyze_pushButton_1,#member_pushButton_1,#logout_button_1 {\n"
"\n"
"margin-left: 0px;\n"
"padding: 8px 3px;\n"
"}\n"
"#logout_button_1 {\n"
"text-align: center8px;\n"
"padding: 8px 15px }\n"
"#analyze_pushButton_1:hover,#member_pushButton_1:hover,#transaction_pushButton_1:hover,#logout_button_1:hover {\n"
"background-color: white}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left_Menu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_Menu.sizePolicy().hasHeightForWidth())
        self.Left_Menu.setSizePolicy(sizePolicy)
        self.Left_Menu.setMinimumSize(QtCore.QSize(165, 0))
        self.Left_Menu.setMaximumSize(QtCore.QSize(165, 16777215))
        self.Left_Menu.setObjectName("Left_Menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Left_Menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_17 = QtWidgets.QFrame(self.Left_Menu)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_17)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_14.setSpacing(13)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        self.label_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/imgs/Assets/image/Group 73.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.frame_14.setFont(font)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(35)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.transaction_pushButton_1 = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.transaction_pushButton_1.setFont(font)
        self.transaction_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/airplay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transaction_pushButton_1.setIcon(icon)
        self.transaction_pushButton_1.setIconSize(QtCore.QSize(25, 25))
        self.transaction_pushButton_1.setObjectName("transaction_pushButton_1")
        self.verticalLayout_5.addWidget(self.transaction_pushButton_1)
        self.member_pushButton_1 = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.member_pushButton_1.setFont(font)
        self.member_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.member_pushButton_1.setIcon(icon1)
        self.member_pushButton_1.setIconSize(QtCore.QSize(25, 25))
        self.member_pushButton_1.setObjectName("member_pushButton_1")
        self.verticalLayout_5.addWidget(self.member_pushButton_1)
        self.analyze_pushButton_1 = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.analyze_pushButton_1.setFont(font)
        self.analyze_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/activity.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analyze_pushButton_1.setIcon(icon2)
        self.analyze_pushButton_1.setIconSize(QtCore.QSize(25, 25))
        self.analyze_pushButton_1.setObjectName("analyze_pushButton_1")
        self.verticalLayout_5.addWidget(self.analyze_pushButton_1)
        self.verticalLayout_6.addWidget(self.frame_16, 0, QtCore.Qt.AlignTop)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.logout_button_1 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        self.logout_button_1.setFont(font)
        self.logout_button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Assets/feather/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_button_1.setIcon(icon3)
        self.logout_button_1.setObjectName("logout_button_1")
        self.horizontalLayout_15.addWidget(self.logout_button_1)
        self.verticalLayout_6.addWidget(self.frame_18)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.verticalLayout_4.addWidget(self.frame_17)
        self.horizontalLayout.addWidget(self.Left_Menu)
        self.right_frame_1 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_frame_1.sizePolicy().hasHeightForWidth())
        self.right_frame_1.setSizePolicy(sizePolicy)
        self.right_frame_1.setStyleSheet("color: black")
        self.right_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame_1.setObjectName("right_frame_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_frame_1)
        self.verticalLayout.setContentsMargins(0, 6, 6, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame_1 = QtWidgets.QFrame(self.right_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_frame_1.sizePolicy().hasHeightForWidth())
        self.top_frame_1.setSizePolicy(sizePolicy)
        self.top_frame_1.setStyleSheet("background-color:rgba(227, 255, 236, 255);\n"
"border-radius: 15px;")
        self.top_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame_1.setObjectName("top_frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.top_frame_1)
        self.verticalLayout_2.setContentsMargins(0, 11, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame_1 = QtWidgets.QFrame(self.top_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame_1.sizePolicy().hasHeightForWidth())
        self.header_frame_1.setSizePolicy(sizePolicy)
        self.header_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame_1.setObjectName("header_frame_1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.header_frame_1)
        self.horizontalLayout_13.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.searchby_frame_1 = QtWidgets.QFrame(self.header_frame_1)
        self.searchby_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchby_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchby_frame_1.setObjectName("searchby_frame_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.searchby_frame_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.searchby_frame_1)
        self.comboBox.setStyleSheet("border-radius:5px;\n"
"border:1px solid;\n"
"padding:0 8px;\n"
"background-color:rgba(142, 255, 150, 255);\n"
"\n"
"font-size: 15px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_13.addWidget(self.searchby_frame_1, 0, QtCore.Qt.AlignTop)
        self.search_frame_1 = QtWidgets.QFrame(self.header_frame_1)
        self.search_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame_1.setObjectName("search_frame_1")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.search_frame_1)
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.search_lineEdit_1 = QtWidgets.QLineEdit(self.search_frame_1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.search_lineEdit_1.setFont(font)
        self.search_lineEdit_1.setStyleSheet("border-radius:10px;\n"
"border:1px solid\n"
"")
        self.search_lineEdit_1.setObjectName("search_lineEdit_1")
        self.horizontalLayout_17.addWidget(self.search_lineEdit_1)
        self.horizontalLayout_13.addWidget(self.search_frame_1)
        self.rightheader_frame_1 = QtWidgets.QFrame(self.header_frame_1)
        self.rightheader_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightheader_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightheader_frame_1.setObjectName("rightheader_frame_1")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.rightheader_frame_1)
        self.horizontalLayout_18.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.search_pushButton_1 = QtWidgets.QPushButton(self.rightheader_frame_1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.search_pushButton_1.setFont(font)
        self.search_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_pushButton_1.setStyleSheet("border-radius:5px;\n"
"border:1px solid;\n"
"padding:0 8px;\n"
"background-color:rgba(142, 255, 150, 255);\n"
"")
        self.search_pushButton_1.setObjectName("search_pushButton_1")
        self.horizontalLayout_18.addWidget(self.search_pushButton_1)
        self.showall_pushButton_1 = QtWidgets.QPushButton(self.rightheader_frame_1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.showall_pushButton_1.setFont(font)
        self.showall_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showall_pushButton_1.setStyleSheet("border-radius:5px;\n"
"border:1px solid;\n"
"padding:0 8px;\n"
"background-color:rgba(142, 255, 150, 255);")
        self.showall_pushButton_1.setObjectName("showall_pushButton_1")
        self.horizontalLayout_18.addWidget(self.showall_pushButton_1)
        self.horizontalLayout_13.addWidget(self.rightheader_frame_1)
        self.verticalLayout_2.addWidget(self.header_frame_1, 0, QtCore.Qt.AlignTop)
        self.table_frame_1 = QtWidgets.QFrame(self.top_frame_1)
        self.table_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame_1.setObjectName("table_frame_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.table_frame_1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.table_frame_1)
        self.tableWidget.setStyleSheet("#tableWidget {\n"
"background-color: white\n"
"}\n"
"QHeaderView::section {\n"
"   border-bottom: 1px solid #dcdcff;\n"
"    text-align: left;\n"
"    padding: 4px 5px;\n"
"background-color: rgb(242, 239, 242);\n"
"}\n"
"QTableWidget::Item {\n"
"    border-bottom: 1px solid #dcdcff;\n"
"    color: #000;\n"
"    padding-left: 3px;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.verticalLayout_8.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.table_frame_1)
        self.verticalLayout.addWidget(self.top_frame_1)
        self.bottom_frame_1 = QtWidgets.QFrame(self.right_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_frame_1.sizePolicy().hasHeightForWidth())
        self.bottom_frame_1.setSizePolicy(sizePolicy)
        self.bottom_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_1.setObjectName("bottom_frame_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottom_frame_1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.back_frame_1 = QtWidgets.QFrame(self.bottom_frame_1)
        self.back_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_frame_1.setObjectName("back_frame_1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.back_frame_1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_pushButton_1 = QtWidgets.QPushButton(self.back_frame_1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.back_pushButton_1.setFont(font)
        self.back_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_pushButton_1.setStyleSheet("#back_pushButton_1 {\n"
"border-radius:10px;\n"
"border:1px solid;\n"
"background-color: rgba(40, 207, 107, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding: 8px 20px;\n"
"}\n"
"#back_pushButton_1:hover {\n"
"background-color: rgb(225, 253, 234);\n"
"color: black;\n"
"}\n"
"")
        self.back_pushButton_1.setObjectName("back_pushButton_1")
        self.horizontalLayout_7.addWidget(self.back_pushButton_1)
        self.refresh_btn_1 = QtWidgets.QPushButton(self.back_frame_1)
        self.refresh_btn_1.setStyleSheet("padding: 12px;\n"
"margin-left: 8px\n"
"")
        self.refresh_btn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/white_icons/Assets/feather(1)/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn_1.setIcon(icon4)
        self.refresh_btn_1.setObjectName("refresh_btn_1")
        self.horizontalLayout_7.addWidget(self.refresh_btn_1)
        self.horizontalLayout_6.addWidget(self.back_frame_1, 0, QtCore.Qt.AlignLeft)
        self.bigrightbottom_frame_1 = QtWidgets.QFrame(self.bottom_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigrightbottom_frame_1.sizePolicy().hasHeightForWidth())
        self.bigrightbottom_frame_1.setSizePolicy(sizePolicy)
        self.bigrightbottom_frame_1.setStyleSheet("padding-left: 5px")
        self.bigrightbottom_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bigrightbottom_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bigrightbottom_frame_1.setObjectName("bigrightbottom_frame_1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.bigrightbottom_frame_1)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.right_bottomframe_1 = QtWidgets.QFrame(self.bigrightbottom_frame_1)
        self.right_bottomframe_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_bottomframe_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_bottomframe_1.setObjectName("right_bottomframe_1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.right_bottomframe_1)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.detail_pushButton_1 = QtWidgets.QPushButton(self.right_bottomframe_1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.detail_pushButton_1.setFont(font)
        self.detail_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detail_pushButton_1.setStyleSheet("#detail_pushButton_1 {\n"
"border-radius:10px;\n"
"border:1px solid;\n"
"background-color: rgba(40, 207, 107, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding: 8px 20px;\n"
"}\n"
"#detail_pushButton_1:hover {\n"
"background-color: rgb(225, 253, 234);\n"
"color: black;\n"
"}\n"
"")
        self.detail_pushButton_1.setObjectName("detail_pushButton_1")
        self.horizontalLayout_10.addWidget(self.detail_pushButton_1, 0, QtCore.Qt.AlignBottom)
        self.deletedata_pushButton_1 = QtWidgets.QPushButton(self.right_bottomframe_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletedata_pushButton_1.sizePolicy().hasHeightForWidth())
        self.deletedata_pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.deletedata_pushButton_1.setFont(font)
        self.deletedata_pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deletedata_pushButton_1.setStyleSheet("#deletedata_pushButton_1 {\n"
"border-radius:10px;\n"
"border:1px solid;\n"
"background-color: rgba(40, 207, 107, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding: 8px 20px;\n"
"}\n"
"#deletedata_pushButton_1:hover {\n"
"background-color: rgb(225, 253, 234);\n"
"color: black;\n"
"}\n"
"\n"
"")
        self.deletedata_pushButton_1.setObjectName("deletedata_pushButton_1")
        self.horizontalLayout_10.addWidget(self.deletedata_pushButton_1, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_9.addWidget(self.right_bottomframe_1)
        self.horizontalLayout_6.addWidget(self.bigrightbottom_frame_1)
        self.verticalLayout.addWidget(self.bottom_frame_1, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.right_frame_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1320, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.transaction_pushButton_1.setText(_translate("MainWindow", "Transaction"))
        self.member_pushButton_1.setText(_translate("MainWindow", "Member"))
        self.analyze_pushButton_1.setText(_translate("MainWindow", "Analyze"))
        self.logout_button_1.setText(_translate("MainWindow", "LOG OUT"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Search by"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TransactionID"))
        self.comboBox.setItemText(2, _translate("MainWindow", "CustomerID"))
        self.comboBox.setItemText(3, _translate("MainWindow", "EmployeeID"))
        self.comboBox.setItemText(4, _translate("MainWindow", "ProductID"))
        self.comboBox.setItemText(5, _translate("MainWindow", "TransactionDate"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Quantity"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Price"))
        self.comboBox.setItemText(8, _translate("MainWindow", "PaymentMethod"))
        self.comboBox.setItemText(9, _translate("MainWindow", "ProductCategory"))
        self.comboBox.setItemText(10, _translate("MainWindow", "DiscountApplied(%)"))
        self.comboBox.setItemText(11, _translate("MainWindow", "TotalAmount"))
        self.search_pushButton_1.setText(_translate("MainWindow", "Search"))
        self.showall_pushButton_1.setText(_translate("MainWindow", "Show all"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TransactionID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CustomerID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "EmployeeID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ProductID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TransactionDate "))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "PaymentMethod"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ProductCategory"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "DiscountApplied(%)"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "TotalAmount"))
        self.back_pushButton_1.setText(_translate("MainWindow", "Back"))
        self.detail_pushButton_1.setText(_translate("MainWindow", "Detail"))
        self.deletedata_pushButton_1.setText(_translate("MainWindow", "Delete Data"))
import Frame.resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
